FROM golang:latest 
EXPOSE 8000
RUN mkdir /app 
ADD . /app/ 
WORKDIR /app 
ENV GOPATH /app
RUN go get "github.com/gin-gonic/gin"; go get "github.com/go-sql-driver/mysql"; go get "github.com/streadway/amqp"; go get github.com/gin-contrib/cors
RUN cd /app/src ; go install CP
CMD ["/app/bin/CP"]
